{{- if .Values.service.headless.enabled }}
apiVersion: v1
kind: Service
metadata:
    name: {{ default (printf "%s-headless" .Release.Name) .Values.service.headless.name }}
    labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
    clusterIP: None
    selector:
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    ports:
        - name: grpc
          port: {{ .Values.service.port }}
          targetPort: grpc
          protocol: TCP
{{- end }}
