replicaCount: 1

image:
    repository: zot.lan/kitti12911/___NAME___
    tag: ""
    digest: ""
    pullPolicy: IfNotPresent

imagePullSecrets:
    - name: zot-registry

env: []

gomemlimit:
    enabled: true
    percentage: 80

reloader:
    enabled: true

podSecurityContext: {}

securityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    capabilities:
        drop:
            - ALL
    seccompProfile:
        type: RuntimeDefault

resources: {}

affinity: {}

topologySpreadConstraints: []

service:
    type: ClusterIP
    port: 8080

configSecret:
    create: true
    name: ""

probes:
    readiness:
        enabled: true
        path: /health
        initialDelaySeconds: 5
        periodSeconds: 10
        timeoutSeconds: 3
        failureThreshold: 3
    liveness:
        enabled: true
        path: /health
        initialDelaySeconds: 15
        periodSeconds: 20
        timeoutSeconds: 3
        failureThreshold: 3

httpRoute:
    enabled: false
    hostnames: []
    parentRefs:
        - name: traefik
          namespace: default
          group: gateway.networking.k8s.io
          kind: Gateway
          sectionName: https
    pathPrefix: /
    filters: []

config:
    service:
        name: ___NAME___
        port: 8080
        shutdown_timeout: 10s

    logging:
        level: info
        add_source: false
        include_trace_id: true

    tracing:
        enabled: true
        endpoint: alloy.observability.svc.cluster.local:4317
        protocol: grpc
        insecure: true
        sample_ratio: 0.1

    profiling:
        enabled: true
        server_address: http://pyroscope.observability.svc.cluster.local:4040
        namespace: ___NAME___
        basic_auth_user: ""
        basic_auth_password: ""
        tenant_id: ""
